### ISSUE TITLE
Is this method suitable for multi-channel images?

### ISSUE THREAD

**Issue by joe1chief** [gvtulder/elasticdeform#1]
![input image](https://fxfactory.com/downloads/docs/noiseindustries/fxfactorypro/Thumbnails/Checkerboard.jpg)
Run following codes on the above image, I get an odd result.
![result](https://s1.ax1x.com/2018/08/18/PfPzB4.png)

```import numpy, imageio, elasticdeform
X = imageio.imread('test_X.jpg')

X_deformed = elasticdeform.deform_random_grid(X, sigma=25, points=3)

imageio.imsave('test_X.png', X)
imageio.imsave('test_X_deformed.png', X_deformed)```

**Comment by gvtulder** [comment]
By default, the deformation is applied to every dimension of the input. So in your RGB image, there's also a deformation between the colour channels. That looks odd.

I've pushed an update that adds an `axis` parameter that you can use to specify the axes that you want to deform. For your example, that would look like this:
```python
X = imageio.imread('testgrid.jpg')
X_deformed = elasticdeform.deform_random_grid(X.astype('float64'),
                                              sigma=25, points=3, axis=(0, 1))
imageio.imsave('test_X.png', X)
imageio.imsave('test_X_deformed.png', X_deformed.clip(0, 255).astype('uint8'))
```
It might be useful to convert the image to a float before computing the deformation, since the uint8 will give you strange rounding and overflow errors. If you do the interpolation in floats the result looks much better:

![test_x_deformed](https://user-images.githubusercontent.com/31510/44304121-34e78000-a353-11e8-89e9-9951399ab6f1.png)

**Comment by joe1chief** [comment]
Thanks a lot!
