### ISSUE TITLE
Need some help with the usage of elastic deformation api

### ISSUE THREAD

**Issue by syedalamabbas** [gvtulder/elasticdeform#4]
I use the follow script to understand the deformation in stereo setting, but I think I am not using it correctly since I am getting inconsistent results. I have read through the documentation and I feel that the script below does something but it doesn't do it right.  What I want to do is simple, X,Y are stereo pair images, and D is the disparity map ground truth from [Middlebury dataset](http://vision.middlebury.edu/stereo/data/), I want to deform image X with D to get hat_Y and see and compare hat_Y and Y. Please advice.

```python
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import elasticdeform
import time
import elasticdeform.tf as etf

# Basic image
img0 = mpimg.imread('im0.png')
X = img0[:,:,1]
print(X.shape)

img1 = mpimg.imread('im1.png')
Y = img1[:,:,1]
print(Y.shape)

# Using disparity map as the displacement 
displacement = mpimg.imread('mask0nocc.png')
Ny, Nx = displacement.shape
print(displacement.shape)

max_D = -255
displacement_Hdef = np.zeros((2, Ny, Nx));
displacement_Hdef[1,:,:] = displacement * max_D
print(displacement_Hdef.shape)

# perform forward deformation 
X_deformed = elasticdeform.deform_grid(X, displacement_Hdef)

# Testing the disparity of the deformation 
plt.subplot(2, 2, 1)
im1 = plt.imshow(X)
plt.title('Left View')
plt.grid()
#im1.set_cmap('nipy_spectral')
plt.subplot(2, 2, 2)
im1 = plt.imshow(displacement)
plt.title('Disparity Map')
plt.grid()
#im1.set_cmap('nipy_spectral')
plt.subplot(2, 2, 3)
im2 = plt.imshow(X_deformed)
plt.title('Deformed along X')
plt.grid()
#im1.set_cmap('nipy_spectral')
plt.subplot(2, 2, 4)
im3 = plt.imshow(Y)
plt.title('Right View')
plt.grid()
#im1.set_cmap('nipy_spectral')
plt.tight_layout()
plt.show()
```
Left 
![image](https://user-images.githubusercontent.com/9631714/56827625-59262580-682d-11e9-95ae-eff5dccea0d3.png)

Right 
![image](https://user-images.githubusercontent.com/9631714/56827634-63e0ba80-682d-11e9-9d81-1551a81aab43.png)

Disparity
![image](https://user-images.githubusercontent.com/9631714/56827645-6e02b900-682d-11e9-91ac-df903cead074.png)

Output from my script:
![image](https://user-images.githubusercontent.com/9631714/56827837-e23d5c80-682d-11e9-8929-2c421e506cfb.png)

**Comment by gvtulder** [comment]
First: I think you might need to change the sign of your displacement map, since the deformation is moving the image in the wrong direction. This simple displacement map would move  everything 128 pixels to the left:
```python
displacement_Hdef = np.array([
    [[0, 0],
     [0, 0]],
    [[128, 128],
     [128, 128]]
])
```
so setting `max_d` to 255 (or 128) would at least map more pixels in the right direction.

Second: I don't have experience with disparity maps, but I think that the discontinuities might cause problems for the elastic deformation. The elastic deformation is not a straightforward pixel-to-pixel mapping, it is an interpolated mapping of control points. In your case, the interpolation will fill the gaps between pixels, which might explain some of the artifacts you see. It needs to fill the pixels that you haven't mapped anything to.

What is the result you're after? Perhaps interpolation is not what you want?
